[package]
name = "libvalhalla"
version = "0.1.0"
edition = "2021"
authors = ["kinkard"]
license = "MIT OR Apache-2.0"

[dependencies]
cxx = "1.0"

[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"
